import os
from dotenv import load_dotenv

load_dotenv()

CONFIG = {
    "BISHOP_BRAND_NAME": os.getenv("BISHOP_BRAND_NAME", "BISHOP"),
    "SLACK_BOT_TOKEN": os.getenv("SLACK_BOT_TOKEN"),
    "SLACK_APP_TOKEN": os.getenv("SLACK_APP_TOKEN"),
    "SLACK_SIGNING_SECRET": os.getenv("SLACK_SIGNING_SECRET"),
    "GEMINI_API_KEY": os.getenv("GEMINI_API_KEY"),
    "GEMINI_CHAT_MODEL": os.getenv("GEMINI_CHAT_MODEL", "gemini-2.5-flash"),
    "MENTION_CHAT_OPENAI_FALLBACK_MODEL": os.getenv("MENTION_CHAT_OPENAI_FALLBACK_MODEL", "gpt-4o-mini"),
    "OPENAI_API_KEY": os.getenv("OPENAI_API_KEY"),
    "FIRECRAWL_API_KEY": os.getenv("FIRECRAWL_API_KEY"),
    "DASHBOARD_API_TOKEN": os.getenv("DASHBOARD_API_TOKEN"),
    "TELEGRAM_BOT_TOKEN": os.getenv("TELEGRAM_BOT_TOKEN"),
    "TELEGRAM_OWNER_ID": os.getenv("TELEGRAM_OWNER_ID"),
    "TELEGRAM_ALLOWED_USERS": os.getenv("TELEGRAM_ALLOWED_USERS"),
    "TELEGRAM_MINIAPP_DIR": os.getenv("TELEGRAM_MINIAPP_DIR", os.path.join(os.getenv("PROJECT_ROOT_DIR", os.getcwd()), "bishopbot-telegram-miniapp")),
    "TELEGRAM_MINIAPP_TITLE": os.getenv("TELEGRAM_MINIAPP_TITLE", "BishopBot Terminal"),
    "BISHOP_MCP_CATALOG_DIR": os.getenv("BISHOP_MCP_CATALOG_DIR", os.path.expanduser("~/BishopTech.dev/bishoptech-api-mcps")),
    "BISHOP_MCP_REGISTRY_PATH": os.getenv("BISHOP_MCP_REGISTRY_PATH", "config/mcp_registry.json"),
    "PRIMARY_LLM": os.getenv("PRIMARY_LLM", "gemini"),
    "SECONDARY_LLM": os.getenv("SECONDARY_LLM", "openai"),
    "PROJECT_ROOT_DIR": os.getenv("PROJECT_ROOT_DIR", os.getcwd()),
    "HERMES_HOME": os.getenv("HERMES_HOME", os.path.expanduser("~/.hermes")),
    "OPENCLAW_HOME": os.getenv("OPENCLAW_HOME", os.path.expanduser("~/.openclaw")),
    "SHARED_SKILLS_DIR": os.getenv("SHARED_SKILLS_DIR", os.path.expanduser("~/.agents/skills")),
    "GEMINI_SKILLS_DIR": os.getenv("GEMINI_SKILLS_DIR", os.path.expanduser("~/.gemini/skills")),
    "REDIS_URL": os.getenv("REDIS_URL"),
    "TASK_QUEUE_NAME": os.getenv("TASK_QUEUE_NAME", "bishopbot_tasks"),
    "GITHUB_TOKEN": os.getenv("GITHUB_TOKEN"),
    "SLACK_NOTIFICATIONS_CHANNEL": os.getenv("SLACK_NOTIFICATIONS_CHANNEL"),
    "GEMINI_CLI_ARGS": os.getenv("GEMINI_CLI_ARGS", "--yolo"),
    "GEMINI_CLI_ARGS_YOLO": os.getenv("GEMINI_CLI_ARGS_YOLO", os.getenv("GEMINI_CLI_ARGS", "--yolo")),
    "CODEX_CLI_ARGS": os.getenv("CODEX_CLI_ARGS", "exec --full-auto"),
    "CODEX_CLI_ARGS_FULL_AUTO": os.getenv("CODEX_CLI_ARGS_FULL_AUTO", os.getenv("CODEX_CLI_ARGS", "exec --full-auto")),
    "CODEX_CLI_ARGS_YOLO": os.getenv("CODEX_CLI_ARGS_YOLO", "--yolo"),
    "GEMINI_PROMPT_TRANSPORT": os.getenv("GEMINI_PROMPT_TRANSPORT", "stdin"),
    "CODEX_PROMPT_TRANSPORT": os.getenv("CODEX_PROMPT_TRANSPORT", "argv"),
    "GOOGLE_CLIENT_SECRETS_PATH": os.getenv("GOOGLE_CLIENT_SECRETS_PATH", "client_secrets.json"),

    # Terminal session tuning
    "TERMINAL_BOOT_DELAY_SECONDS": os.getenv("TERMINAL_BOOT_DELAY_SECONDS", "7"),
    "GEMINI_BOOT_DELAY_SECONDS": os.getenv("GEMINI_BOOT_DELAY_SECONDS", "10"),
    "CODEX_BOOT_DELAY_SECONDS": os.getenv("CODEX_BOOT_DELAY_SECONDS", "5"),
    "TERMINAL_PROMPT_ENTER_DELAY_SECONDS": os.getenv("TERMINAL_PROMPT_ENTER_DELAY_SECONDS", "5"),
    "TERMINAL_READY_WAIT_SECONDS": os.getenv("TERMINAL_READY_WAIT_SECONDS", "25"),
    "TERMINAL_POLL_INTERVAL_SECONDS": os.getenv("TERMINAL_POLL_INTERVAL_SECONDS", "40"),
    "TERMINAL_TAIL_LINES_SLACK": os.getenv("TERMINAL_TAIL_LINES_SLACK", "15"),
    "TERMINAL_TAIL_LINES_WHATSAPP": os.getenv("TERMINAL_TAIL_LINES_WHATSAPP", "40"),
    "TERMINAL_ACTIVATE_ON_LAUNCH": os.getenv("TERMINAL_ACTIVATE_ON_LAUNCH", "false"),
    "TERMINAL_ACTIVATE_ON_INPUT": os.getenv("TERMINAL_ACTIVATE_ON_INPUT", "false"),
    "TERMINAL_CLOSE_RECOVERY_GRACE_SECONDS": os.getenv("TERMINAL_CLOSE_RECOVERY_GRACE_SECONDS", "20"),
    "TERMINAL_STATE_HEARTBEAT_SECONDS": os.getenv("TERMINAL_STATE_HEARTBEAT_SECONDS", "3"),
    "TERMINAL_STATE_HEARTBEAT_STALE_SECONDS": os.getenv("TERMINAL_STATE_HEARTBEAT_STALE_SECONDS", "15"),
    "SESSION_LOG_DIR": os.getenv("SESSION_LOG_DIR", "logs/sessions"),
    "SESSION_STATE_DIR": os.getenv("SESSION_STATE_DIR", "logs/session-state"),
    "SESSION_OUTPUT_DIR": os.getenv("SESSION_OUTPUT_DIR", "logs/session-output"),

    # WhatsApp Cloud API (Meta)
    "WHATSAPP_ENABLED": os.getenv("WHATSAPP_ENABLED", "false"),
    "WHATSAPP_DEBUG": os.getenv("WHATSAPP_DEBUG", "false"),
    "WHATSAPP_VERIFY_TOKEN": os.getenv("WHATSAPP_VERIFY_TOKEN"),
    "WHATSAPP_ACCESS_TOKEN": os.getenv("WHATSAPP_ACCESS_TOKEN"),
    "WHATSAPP_PHONE_NUMBER_ID": os.getenv("WHATSAPP_PHONE_NUMBER_ID"),
    # Optional: webhook signature verification (X-Hub-Signature-256)
    "WHATSAPP_APP_SECRET": os.getenv("WHATSAPP_APP_SECRET"),
}
